match: >-
  ^%{TIMESTAMP_ISO8601:timestamp}\s+%{LOGLEVEL:level}\s+\[%{DATA:logger}\]\s+\[pid=%{NUMBER:pid:int}\s+thread_id=%{NUMBER:thread_id:int}\s+thread_name="%{DATA:thread_name}"\s+task_id=%{DATA:task_id}\s+request_id=%{DATA:request_id}\]\s+%{GREEDYDATA:message}$

patterns:
  MULTILINE_DATA: '[\s\S]*'

multiline:
  pattern: '^%{TIMESTAMP_ISO8601}'
  negate: true
  what: previous
  auto_flush_interval: 2
  max_lines: 500
  max_bytes: 10485760
  skip_newline: false
